### ISSUE TITLE
dome should create plans directory

### ISSUE THREAD

**Issue by caoilte** [ITV/domed-city#29]
When you run dome for the first time it generally errors because you don't have a plans directory.

We could create the plans directory every where we have TF files but I think it would be better if dome just made sure the directory existed as part of the execution process (this would have the added advantage of allowing us to add plans to our gitignore)

**Comment by madAndroid** [comment]
This is implemented in https://github.com/ITV/domed-city/commit/01ea27da88b8963b1d6d3c5611aaa3360df7e662 - but it's in a pending PR: https://github.com/ITV/domed-city/pull/33 - will close this issue when that PR's been merged in
