### ISSUE TITLE
we should be forced to specify our version of TF

### ISSUE THREAD

**Issue by caoilte** [ITV/domed-city#31]
Apols if I mis-state the problem here.

As I understand it dome will work with whatever version of terraform is installed on your system. This is dangerous (we've seen lots of problems introduced by different people in the team accidentally using different versions in the past).

We should have somewhere (any itv.yaml at a higher directory?) where dome requires you to lock down your terraform version.

If the wrong version is installed it could then fail early and tell you to go upgrade.

**Comment by bsnape** [comment]
We have discussed this internally before and yes we agree.

We can enforce the version in the `itv.yaml`

**Comment by caoilte** [comment]
@bsnape apologies. We discovered that Terraform now does this itself. (maybe support was only added recently).

So dome doesn't need to do anything (i will close this ticket).

**Comment by bsnape** [comment]
ah cool - do you have details @caoilte ? perhaps this was part of 0.7
